.\"	$scrotwm$
.\"
.\" Copyright (c) 2009 Marco Peereboom <marco@peereboom.us>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt SCROTWM 1
.Os
.Sh NAME
.Nm scrotwm
.Nd small dynamic tiling window manager for X11.
.Sh SYNOPSIS
.Nm scrotwm
.Sh DESCRIPTION
.Nm
is a minimalistic window manager that tries to stay out of the way so that
valuable screen real estate can be used for much more important stuff.
It has sane defaults and does not require one to learn a language to do any
configuration.
It was written by hackers for hackers and it strives to be small, compact and
fast. 
.Pp
The following notation is used throughout this page:
.Pp
.Bl -tag -width Ds -offset indent -compact
.It Ic M
Meta
.It Ic S
Shift
.It Ic [Name]
Named key
.It Ic M1
Mouse button 1
.El
.Pp
.Nm
is very simple in its use.
Most of the actions are initiated via keybindings.
The current keybindings are described below:
.Pp
.Bl -tag -width "C-M-EscapeXXX" -offset indent -compact
.It Ic M-S-[Return]
Spawn a new terminal.
.It Ic M-p
Menu.
.It Ic M-S-q
Quit.
.It Ic M-q
Restart
.Nm .
.It Ic M-[Space]
Cycle layout.
.It Ic M-S-[Space]
Reset layout.
.It Ic M-h
Shrink master area.
.It Ic M-l
Grow master area.
.It Ic M-,
Add windows to master area.
.It Ic M-.
Remove windows from master area.
.It Ic M-[Return]
Move current window to master area.
.It Ic M-j
Focus next window in workspace.
.It Ic M-[Tab]
Focus next window in workspace.
.It Ic M-k
Focus previous window in workspace.
.It Ic M-S-[Tab]
Focus previous window in workspace.
.It Ic M-m
Focus on main window in workspace.
.It Ic M-S-j
Swap with next window in workspace.
.It Ic M-S-k
Swap with previous window in workspace.
.It Ic M-b
Toggle status bar in all workspaces.
.It Ic M-S-x
Destroy current window in workspace.
.It Ic M-[Number]
Switch to workspace [Number].
.It Ic M-S-[Number]
Move current window to workspace [Number].
.It Ic M-[RighArrow]
Switch to next workspace with a window in it.
.It Ic M-[LeftArrow]
Switch to previous workspace with a window in it.
.It Ic M-s
Take screenshot of entire screen (if enabled).
.It Ic M-S-s
Take screenshot of selected window (if enabled).
.It Ic M1
Focus window.
.El
.Pp
.Pp
.Sh FILES
.Bl -tag -width Ds
.It Pa ~/.scrotwm.conf
This file contains user specific settings.
.It Pa /etc/scrotwm.conf
This file contains global settings.
.El
.Pp
.Nm
first tries to open the user specific file.
If that file is unavailable it tries to open the global file next.
.Pp
The format of the file is <keyword> = <setting>.
E.g. color_focus = red.
.Pp
Enabling or disabling an option is done by using 1 or 0 respectively.
.Pp
The file supports the following keywords:
.Bl -tag -width "C-M-EscapeXXX" -offset indent -compact
.It Ic color_focus
Border color of the currently focussed window.
.It Ic color_unfocus
Border color of unfocussed windows.
.It Ic bar_enabled
Enable or disable status bar.
.It Ic bar_border[x]
Color of the status bar border in screen x.
.It Ic bar_color[x]
Color of the status bar window in screen x.
.It Ic bar_font_color[x]
Color of the font in status bar in screen x.
.It Ic bar_font
Status bar font.
.It Ic bar_action
External script that populates additional information in the status bar such as
battery life etc.
.It Ic bar_delay
Update frequency, in seconds, of external script that populates the status bar.
.It Ic spawn_term
External application that gets spawned when M-S-[Return] is used.
.It Ic dialog_ratio
Some applications have dialog windows that are too small to be useful.
This ratio is the screen size as to what they will be resized.
E.g 0.6 is 60% of the physical screen size.
.It Ic screenshot_enabled
Enable or disable screenshot capability.
.It Ic screenshot_app
Set to the script that will take screenshots.
It will be called with "full" or "window" as parameter 1 to indicate what
screenshot action is expected.
The script shall handle those cases accordingly.
.El
.Pp
Colors need to be specified per the
.Xr XQueryColor 4
specification and fonts need to be specified per the
.Xr XQueryFont 4
specification.
.Sh BUGS
Currently the menu, invoked with M-p, depends on dmenu.
.Sh AUTHORS
.An -nosplit
.Pp
.Nm
was written by
.An Marco Peereboom Aq marco@peereboom.us
and
.An Ryan Thomas McBride Aq mcbride@countersiege.com .
.Sh HISTORY
.Nm
was inspired by xmonad & dwm.
