/*
 * Copyright (c) 2011 Conformal Systems LLC <info@conformal.com>
 *
 * Permission to use, copy, modify, and distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */


#ifndef SCROTWM_VERSION_H
#define SCROTWM_VERSION_H

#define SCROTWM_STR(x)		#x
#define SCROTWM_STRINGIZE(x)	SCROTWM_STR(x)

#define SCROTWM_MAJOR		0
#define SCROTWM_MINOR		10
#define SCROTWM_PATCH		0
#define SCROTWM_VERSION		SCROTWM_STRINGIZE(SCROTWM_MAJOR) "." \
				SCROTWM_STRINGIZE(SCROTWM_MINOR) "." \
				SCROTWM_STRINGIZE(SCROTWM_PATCH)

#endif /* SCROTWM_VERSION_H */

