#ifndef TAILQ_END
#define TAILQ_END(head)			NULL
#endif

#ifndef SIMPLEQ_HEAD
#define SIMPLEQ_HEAD			STAILQ_HEAD
#define SIMPLEQ_HEAD_INITIALIZER	STAILQ_HEAD_INITIALIZER
#define SIMPLEQ_ENTRY			STAILQ_ENTRY
#define SIMPLEQ_INIT			STAILQ_INIT
#define SIMPLEQ_INSERT_AFTER		STAILQ_INSERT_AFTER
#define SIMPLEQ_INSERT_HEAD		STAILQ_INSERT_HEAD
#define SIMPLEQ_INSERT_TAIL		STAILQ_INSERT_TAIL
#define SIMPLEQ_EMPTY			STAILQ_EMPTY
#define SIMPLEQ_FIRST			STAILQ_FIRST
#define SIMPLEQ_REMOVE_AFTER		STAILQ_REMOVE_AFTER
#define SIMPLEQ_REMOVE_HEAD		STAILQ_REMOVE_HEAD
#define SIMPLEQ_FOREACH			STAILQ_FOREACH
#define SIMPLEQ_END(head)		NULL
#endif
