.\" Copyright (c) 2009 Marco Peereboom <marco@peereboom.us>
.\" Copyright (c) 2009 Darrin Chandler <dwchandler@stilyagin.com>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: February 15 2012 $
.Dt SPECTRWM 1
.Os
.Sh NOMBRE
.Nm spectrwm
.Nd es un manejador de ventanas para X11
.Sh SYNOPSIS
.Nm spectrwm
.Sh DESCRIPCIÓN
.Nm
es un manejador de ventanas super minimalista para X11. Intenta no superponer
las ventanas para que las mismas puedan usarse de manera eficiente y para
cosas mas importantes.
Tiene configuraciones normales y no requiere que sepas un lenguaje de
programacion para configurarlo. Esta escrito por hackers para hackers y apunta
a ser pequeño, compacto y rápido.
.Pp
Cuando
.Nm
inicia, lo primero que hace es leer el archivo de configuracion,
.Pa spectrwm.conf .
Ver
.Sx ARCHIVOS DE CONFIGURACIÓN
.
.Pp
La siguiente anotacion se usa a través de esta pagina:
.Pp
.Bl -tag -width Ds -offset indent -compact
.It Cm M
Meta
.It Cm S
Shift
.It Aq Cm Name
Nombre de tecla
.It Cm M1
Boton 1 del mouse
.It Cm M3
Boton 3 del mouse
.El
.Pp
.Nm
es muy simple de usar.
La mayoria de las acciones se hacen con los mapeos (bindings) de mouse
o teclado.
Ver la sección de
.Sx BINDINGS
para las personalizaciones y configuraciones por defecto.
.Sh ARCHIVOS DE CONFIGURACIÓN
.Nm
primero trata de abrir el archivo por defecto en el directorio del usuario,
.Pa ~/.spectrwm.conf .
Si ese archivo no esta disponible,
luego trata de abrir el archivo global de configuracion
.Pa /etc/spectrwm.conf .
.Pp
El formato del archivo es \*(Lttecla\*(Gt = \*(Ltconfiguracion\*(Gt.
Por ejemplo:
.Pp
.Dl color_focus = red
.Pp
Habilitamos o deshabilitamos la opción usando 1 o 0 respectivamente.
.Pp
El archivo soporta las siguientes palabras clave:
.Pp
.Bl -tag -width "title_class_enabledXXX" -offset indent -compact
.It Cm autorun
Inicia una aplicacion en un escritorio en particular al primer inicio.
Definido por el formato ws[<idx>]:aplicacion, ej. ws[2]:xterm lanza
xterm en el escritorio 2.
.It Cm color_focus
Color del borde de la ventana en foco.
.It Cm color_unfocus
Color del borde de la ventana fuera de foco.
.It Cm bar_enabled
Habilitar o deshabilitar la barra de estado.
.It Cm bar_border Ns Bq Ar x
Color del borde de la barra de estado en pantalla.
.Ar x .
.It Cm bar_border_width
Setea el grosor de la barra de estado en pixels.
Deshabilitado seteando 0.
.It Cm bar_color Ns Bq Ar x
Color de la ventana de la barra de estado en pantalla.
.Ar x .
.It Cm bar_font_color Ns Bq Ar x
Color de la fuente en la barra de estado en pantalla.
.Ar x .
.It Cm bar_font
Fuente de la barra de estado.
.It Cm bar_action
Scripts externos con populares agregados de información para la barra
de estado, como la vida de la bateria.
.It Cm bar_at_bottom
Puedes posicionar la statusbar en la parte inferior de la pantalla.
.It Cm stack_enabled
Habilitar o deshabilitar mostrar el algoritmo de apilamiento en la barra
de estado.
.It Cm clock_enabled
Habilitar o deshabilitar el reloj en la barra de estado, deshabilitado
por defecto con un 0, para usar el reloj de la barra de estado
(bar_action)
.Pa bar_action
script.
.It Cm dialog_ratio
Algunas aplicaciones tienen ventanas de dialogo muy pequeñas como para
ser usables. Este relación (ratio) es el tamaño de la pantalla, por
ejemplo 0.6 es 60% del tamaño físico de la pantalla.
.It Cm layout
Selecciona una disposicion para usar en el primer inicio.
Definido con el formato
ws[idx]:master_grow:master_add:stack_inc:layout:always_raise:stack_mode,
ej.
ws[2]:-4:0:1:0:horizontal setea el escritorio 2 en horizontal, el stack
principal y reduce 4 puntos agregando una ventana al stack, mientras
mantiene el comportamiento de ventanas flotantes.
Modos posible de stack_mode
.Pa vertical ,
.Pa horizontal
and
.Pa fullscreen .
.Pp
Ver
.Pa master_grow ,
.Pa master_shrink ,
.Pa master_add ,
.Pa master_del ,
.Pa stack_inc ,
.Pa stack_del ,
y
.Pa always_raise
para mas informacion.
Tenga en cuenta que las opciones de stack son complicados y tienen
efectos secundarios.
Uno debe familiarizarse con estos comandos antes de experimentar con la
opcion
.Pa layout
.Pp
Esta opcion no necesita un reinicio.
.It Cm region
Acomodar una region personalizada, removiendo cualquier autodeteción de
regiones que ocupe el espacio en la pantalla.
Definiendo el formato screen[<idx>]:WIDTHxHEIGHT+X+Y,
e.g.\& screen[1]:800x1200+0+0.
.It Cm term_width
Setear un ancho minimo preferido para la terminal.
Si el valor es mayor que 0,
.Nm
intentará ajustar el tamaño de la fuente de la terminal para mantener
el ancho de la terminal por encima de este número cuando la ventana
cambia de tamaño.
Actualmente solo es soportado por
.Xr xterm 1
El binario de
.Xr xterm 1
no debe ser un setuid o setgid, que no sea el que viene por defecto en
la mayoria de los sistemas.
Los usuarios pueden necesitar setear program[term] (ver la sección
.Sx PROGRAMAS
) para usar una copia alternativa del binario de
.Xr xterm 1
sin el seteo del setgid.
.It Cm title_class_enabled
Habilitar o deshabilitar la clase de ventana en la barre de estado.
Habilitado seteando 1
.It Cm title_name_enabled
Habilitar o deshabilita el titulo de la ventana en la barra de estado.
Habilitado seteando 1
.It Cm urgent_enabled
Habilitar o deshabilitar el aviso de urgencia.
Tenga en cuenta que muchos emuladores de terminal requieren de este
parametro habilitado para que funcione.
En xterm, por ejemplo, hay que agregar la siguiente linea
.Pa xterm.urgentOnBell: true
to
.Pa .Xdefaults .
.It Cm window_name_enabled
Habilitar o deshabilita el nombre de la ventana en la barra de estado.
Habilitado seteando 1
.It Cm verbose_layout
Habilitar o deshabilita la notificacion del area principal y el
stack en la barra de estado.
Habilitado seteandolo a 1.
.It Cm modkey
Cambiar mod key.
Mod1 generalmente es la tecla ALT y Mod4 la tecla de windows en una PC.
.It Cm focus_mode
Usando el valor de
.Pa follow_cursor
puedes hacer que el manejador de ventanas
se enfoque en la ventana cuando el cursor pase por arriba de las mismas o
bien cambiando de estacion de trabajo.
.It Cm disable_border
Remueve el borde de una sola ventana cuando la barra de estado esta desactivada.
.It Cm border_width
Setea el grosor del borde de la ventana en pixels.
Deshabilitar todos los bordes seteandolo a 0.
.It Cm program Ns Bq Ar p
Definir una nueva accion para ejecutar un programa.
.Ar p .
Ver la sección de
.Sx PROGRAMAS
.It Cm bind Ns Bq Ar x
Combinación de teclas para una acción
.Ar x .
Ver la sección
.Sx BINDINGS
.It Cm quirk Ns Bq Ar c:n
Agregar un "quirk" (o forzados) para ventanas con clase
.Ar c
y nombre
.Ar n .
Ver la sección
.Sx QUIRKS
.El
.Pp
Los colores deben ser especificados por la especificación
.Xr XQueryColor 3
y las fuentes por la especificación
.Xr XQueryFont 3
.Sh PROGRAMAS
.Nm
te permite definir acciones personales para lanzar los programas que
quieras y luego obligar a la misma con una función de acciones.
Ver la sección
.Sx BINDINGS
.Pp
Los programas por defecto se describen acá:
.Pp
.Bl -tag -width "screenshot_wind" -offset indent -compact
.It Cm term
xterm
.It Cm screenshot_all
screenshot.sh completo
.It Cm screenshot_wind
screenshot.sh por ventana
.It Cm lock
xlock
.It Cm initscr
initscreen.sh
.It Cm menu
dmenu_run \-fn $bar_font \-nb $bar_color \-nf $bar_font_color \-sb $bar_border \-sf $bar_color
.El
.Pp
Los programas en la configuración personal, se especifican aca:
.Pp
.Dl program[<nombre>] = <progpath> [<arg> [... <arg>]]
.Pp
.Aq nombre
es un identificador, no genera conflictos con ninguna accion o palabra
clave,
.Aq progpath
es la ruta al programa, y
.Aq arg
es ninguno o mas de un argumento para el programa.
.Pp
Las siguientes variables de configuracion en
.Nm
(ver
.Sx ARCHIVOS DE CONFIGURACIÓN
),
y pueden ser usadas en los campos de
.Aq arg
como asi tambien sustituidas por valores al momento del inicio de un
programa:
.Pp
.Bl -tag -width "$bar_font_color" -offset indent -compact
.It Cm $bar_border
.It Cm $bar_color
.It Cm $bar_font
.It Cm $bar_font_color
.It Cm $color_focus
.It Cm $color_unfocus
.El
.Pp
Ejemplo:
.Bd -literal -offset indent
program[ff] = /usr/local/bin/firefox http://spectrwm.com.ar/
bind[ff] = Mod+f # Ahora Mod+F inicia firefox
.Ed
.Pp
Para deshacer lo anterior:
.Bd -literal -offset indent
bind[] = Mod+f
program[ff] =
.Ed
.Sh BINDINGS
.Nm
provee muchas funciones (o acciones) accesibles por medio de la
asignación (bindings) de teclas o el mouse.
.Pp
Las corrientes asignaciones (bindings) del mouse son:
.Pp
.Bl -tag -width "M-j, M-<TAB>XXX" -offset indent -compact
.It Cm M1
Enfoco una ventana
.It Cm M-M1
Muevo una ventana
.It Cm M-M3
Redimenciono una ventana
.It Cm M-S-M3
Redimenciono una ventana hasta que quede centrada
.El
.Pp
Las corrientes asignaciones (bindings) de teclas son:
.Pp
.Bl -tag -width "M-j, M-<TAB>XXX" -offset indent -compact
.It Cm M-S- Ns Aq Cm Return
term
.It Cm M-p
menu
.It Cm M-S-q
quit
.It Cm M-q
restart
.Nm
.It Cm M- Ns Aq Cm Space
cycle_layout
.It Cm M-S- Ns Aq Cm Space
reset_layout
.It Cm M-h
master_shrink
.It Cm M-l
master_grow
.It Cm M-,
master_add
.It Cm M-.
master_del
.It Cm M-S-,
stack_inc
.It Cm M-S-.
stack_del
.It Cm M- Ns Aq Cm Return
swap_main
.It Xo
.Cm M-j ,
.Cm M- Ns Aq Cm TAB
.Xc
focus_next
.It Xo
.Cm M-k ,
.Cm M-S- Ns Aq Cm TAB
.Xc
focus_prev
.It Cm M-m
focus_main
.It Cm M-S-j
swap_next
.It Cm M-S-k
swap_prev
.It Cm M-b
bar_toggle
.It Cm M-x
wind_del
.It Cm M-S-x
wind_kill
.It Cm M- Ns Aq Ar n
.Pf ws_ Ns Ar n
.It Cm M-S- Ns Aq Ar n
.Pf mvws_ Ns Ar n
.It Cm M- Ns Aq Cm Right
ws_next
.It Cm M- Ns Aq Cm Left
ws_prev
.It Cm M-a
ws_prior
.It Cm M-S- Ns Aq Cm Right
screen_next
.It Cm M-S- Ns Aq Cm Left
screen_prev
.It Cm M-s
screenshot_all
.It Cm M-S-s
screenshot_wind
.It Cm M-S-v
version
.It Cm M-t
float_toggle
.It Cm M-S Aq Cm Delete
lock
.It Cm M-S-i
initscr
.It Cm M-w
iconify
.It Cm M-S-w
uniconify
.It Cm M-S-r
always_raise
.It Cm M-v
button2
.It Cm M--
width_shrink
.It Cm M-=
width_grow
.It Cm M-S-
height_shrink
.It Cm M-S-=
height_grow
.It Cm M-[
move_left
.It Cm M-]
move_right
.It Cm M-S-[
move_up
.It Cm M-S-]
move_down
.El
.Pp
El nombre de las acciónes descripta a continuación:
.Pp
.Bl -tag -width "M-j, M-<TAB>XXX" -offset indent -compact
.It Cm term
Ejecutar una terminal
(ver
.Sx PROGRAMAS
)
.It Cm menu
Menu
(ver
.Sx PROGRAMAS
)
.It Cm quit
Salir
.Nm
.It Cm restart
Reiniciar
.Nm
.It Cm cycle_layout
Disposición de las ventanas
.It Cm reset_layout
Reiniciar la disposición de las ventanas
.It Cm master_shrink
Achicar la region principal
.It Cm master_grow
Agrandar la region principal
.It Cm master_add
Agregar una ventana a la region principal
.It Cm master_del
Quitar una ventana de la region principal
.It Cm stack_inc
Agregar columnas/filas a las pilas
.It Cm stack_del
Quitar columnas/filas de las pilas
.It Cm swap_main
Mover la ventana corriente a la region principal
.It Cm focus_next
Enfocar la proxima ventana en la estación de trabajo
.It Cm focus_prev
Enfocar la anterior ventana en la estación de trabajo
.It Cm focus_main
Enfocar en la ventana principal de la estación de trabajo
.It Cm swap_next
Ejecutar con la siguiente ventana en la estación de trabajo
.It Cm swap_prev
Ejecutar con la anterior ventana en la estación de trabajo
.It Cm bar_toggle
Cambiar la barra de estado en todas las estaciones de trabajo
.It Cm wind_del
Borrar la ventana corriente en la estación de trabajo
.It Cm wind_kill
Destruir la ventana corriente en la estación de trabajo
.It Cm ws_ Ns Ar n
Cambiar entre estaciones de trabajo
.Ar n ,
donde
.Ar n
es 1 por 10
.It Cm mvws_ Ns Ar n
Mover la ventana corriente a una estación de trabajo
.Ar n ,
donde
.Ar n
es 1 por 10
.It Cm ws_next
Cambiar a la proxima estación de trabajo con una ventana en ella
.It Cm ws_prev
Cambiar a la anterior estación de trabajo con una ventana en ella
.It Cm screen_next
Mover el puntero a la proxima region
.It Cm screen_prev
Mover el puntero a la anterior region
.It Cm screenshot_all
Tomar una captura de pantalla de todo la pantalla (si esta habilitado)
(ver
.Sx PROGRAMAS
)
.It Cm screenshot_wind
Tomar una captura de pantalla de la ventana seleccionada (si esta habilitado)
(ver
.Sx PROGRAMAS
)
.It Cm version
Mostrar la version en la barra de estado
.It Cm float_toggle
Mostar la ventana en foco entre las flotantes y acomodadas
.It Cm lock
Bloquear pantalla
(ver
.Sx PROGRAMAS
)
.It Cm initscr
Reiniciar la pantalla
(ver
.Sx PROGRAMAS
)
.It Cm iconify
Minimiza (unmap) la ventana en foco.
.It Cm uniconify
Maximiza (map) la ventana seleccionada por dmenu.
.It Cm always_raise
Cuando se establece las ventanas en cascada se esconden las
ventanas flotantes.
.It Cm button2
Falsifica el boton del medio del mouse.
.It Cm width_shrink
Reducir el ancho de una ventana flotante.
.It Cm width_grow
Agranda el ancho de una ventana flotante.
.It Cm height_shrink
Reducir la altura de una ventana flotante.
.It Cm height_grow
Agranda la altura de una ventana flotante.
.It Cm move_left
Mueve la ventana flotante un paso a la izquierda.
.It Cm move_right
Mueve la ventana flotante un paso a la derecha.
.It Cm move_up
Mueve la ventana flotante un paso arriba.
.It Cm move_down
Mueve la ventana flotante un paso abajo.
.El
.Pp
Personalizar mapeos (bindings) en el archivo de configuración:
.Pp
.Dl bind[<accion>] = <teclas>
.Pp
.Aq accion
una de las acciones listadas (o ninguna) y
.Aq teclas
una o mas teclas modificadas (puede ser ninguna tambien)
(MOD, Mod1, Shift, etc.) y una o mas teclas normales
(b, barra espaciadora, etc.), separadas por un "+".
Por ejemplo:
.Bd -literal -offset indent
bind[reset] = Mod4+q # combinación Tecla de Windows + q reinicia
bind[] = Mod1+q # des-hace la combinación Alt + q
.Ed
.Pp
Multiples combinaciones de teclas pueden hacer lo mismo.
.Sh QUIRKS
.Nm
te da "quirks" (o forzados) ventanas que tienen que ser tratas de manera especial,
como por ejemplo, popups, aplicaciones de pantalla completa, etc.
.Pp
Los "quirks" (o forzados) por defecto son:
.Pp
.Bl -tag -width "OpenOffice.org N.M:VCLSalFrame<TAB>XXX" -offset indent -compact
.It Firefox\-bin:firefox\-bin
TRANSSZ
.It Firefox:Dialog
FLOAT
.It Gimp:gimp
FLOAT + ANYWHERE
.It MPlayer:xv
FLOAT + FULLSCREEN
.It OpenOffice.org 2.4:VCLSalFrame
FLOAT
.It OpenOffice.org 3.1:VCLSalFrame
FLOAT
.It pcb:pcb
FLOAT
.It xine:Xine Window
FLOAT + ANYWHERE
.It xine:xine Panel
FLOAT + ANYWHERE
.It xine:xine Video Fullscreen Window
FULLSCREEN + FLOAT
.It Xitk:Xitk Combo
FLOAT + ANYWHERE
.It Xitk:Xine Window
FLOAT + ANYWHERE
.It XTerm:xterm
XTERM_FONTADJ
.El
.Pp
Los "quirks" (o forzados) se describen a continuación:
.Pp
.Bl -tag -width "XTERM_FONTADJ<TAB>XXX" -offset indent -compact
.It FLOAT
Esta ventana no tiene que ser acomodada, pero le permitimos flotar libremente.
.It TRANSSZ
Ajusta el tamaño de las ventanas transitorias que son demasiado pequeñas utilizando dialog_ratio
(ver
.Sx ARCHIVOS DE CONFIGURACIÓN ) .
.It ANYWHERE
Permite que la ventana se ponga donde quiera.
.It XTERM_FONTADJ
Ajusta las fuentes de xterm cuando se redimenciona.
.It FULLSCREEN
Quita el borde para permitir las ventanas en pantalla completa.
.It FOCUSPREV
El enfoque de salida fuerza la solicitud de aplicacisn que
anteriormente se centraba en la aplicacion anterior del stack.
.El
.Pp
Las configuraciones de "quirks" (o forzados) en el archivo de configuración se ven a continuación:
.Pp
.Dl quirk[<clases>:<nombre>] = <quirk> [ + <quirk> ... ]
.Pp
.Aq clases
y
.Aq nombre
especifica la ventana en la cual el "quirk(s)" (o forzados) se aplica, y
.Aq quirk
es uno de los "quirks" (o forzados) de la lista.
Por ejemplo:
.Bd -literal -offset indent
quirk[MPlayer:xv] = FLOAT + FULLSCREEN # dejamos que mplayer funcione libremente
quirk[pcb:pcb] = NONE  # borramos el quirk existente
.Ed
.Pp
Podes obtener
.Aq clases
y
.Aq nombre
corriendo el programa xprop(1) y luego clickear en la ventana que quieras.
En el proximo ejemplo, podremos verlo en acción con una ventana de Firefox:
.Bd -literal -offset indent
$ xprop | grep WM_CLASS
WM_CLASS(STRING) = "Navigator", "Firefox"
.Ed
.Sh EWMH
.Nm
parcialmente implementa los Consejos de ventana extendido Manager (EWMH) especificacion.
Esto permite el control de las ventanas, asi como
.Nm
si a partir de scripts y programas externos. Esto se logra mediante
.Nm
responder a ciertos eventos ClientMessage. Desde la terminal de estos eventos
se puede enviar facilmente el uso de herramientas tales como
.Xr wmctrl 1
y
.Xr xdotool 1 .
para el
formato real de estos eventos ClientMessage, consulte la especificacion EWMH.
.Pp
La Identificacion de la ventana actualmente enfocada se almacena en el _NET_ACTIVE_WINDOW
propiedad de la ventana raiz. Esto puede ser usado por ejemplo para recuperar el
titulo de la ventana activa con
.Xr xprop 1
y
.Xr grep 1 :
.Bd -literal -offset indent
$ WINDOWID=`xprop \-root _NET_ACTIVE_WINDOW | grep \-o "0x.*"`
$ xprop \-id $WINDOWID WM_NAME | grep \-o "\\".*\\""
.Ed
.Pp
Una ventana se puede enfocar mediante el envio de un mensaje del cliente _NET_ACTIVE_WINDOW
a la ventana principal. Por ejemplo, usando
.Xr wmctrl 1
para enviar el mensaje
(suponiendo que 0x4a0000b es el ID de la ventana para ser especifico):
.Bd -literal -offset indent
$ wmctrl \-i \-a 0x4a0000b
.Ed
.Pp
Ventanas se pueden cerrar mediante el envmo de un mensaje del cliente _NET_CLOSE_WINDOW
a la ventana principal. Por ejemplo, usando
.Xr wmctrl 1
para enviar el mensaje
(suponiendo que 0x4a0000b es el ID de la ventana se cierre):
.Bd -literal -offset indent
$ wmctrl \-i \-c 0x4a0000b
.Ed
.Pp
Las ventanas se pueden flotar y flotar sin-mediante la adicion o eliminacion de la
_NET_WM_STATE_ABOVE atom desde _NET_WM_STATE la propiedad de la ventana
Esto se puede lograr mediante el envio de un mensaje a los clientes _NET_WM_STATE
raiz de la ventana. Por ejemplo, el siguiente cambia el estado de la flota.
.Xr wmctrl 1
para enviar el mensaje (suponiendo que 0x4a0000b es el ID de la ventana flotante
o no-flotante):
.Bd -literal -offset indent
$ wmctrl \-i \-r 0x4a0000b \-b toggle,_NET_WM_STATE_ABOVE
.Ed
.Pp
Ventanas flotantes tambien se puede cambiar el tamano y movido por el envio de un
_NET_MOVERESIZE_WINDOW Mensaje del cliente de la ventana raiz. Por ejemplo,
uso
.Xr wmctrl 1
para enviar el mensaje (suponiendo que 0x4a0000b es el ID de
la ventana a redimensionar / mover):
.Bd -literal -offset indent
$ wmctrl \-i \-r 0x4a0000b \-e 0,100,50,640,480
.Ed
.Pp
Esto mueve la ventana de (100,50) y cambia el tamaqo a 640x480.
.Pp
Todos los eventos _NET_MOVERESIZE_WINDOW recibido por las ventanas apiladas se ignoran.
.Sh SIGNALS
Enviando
.Nm
una senal de HUP reinicia spectrwm.
.Sh ARCHIVOS
.Bl -tag -width "/etc/spectrwm.confXXX" -compact
.It Pa ~/.spectrwm.conf
.Nm
archivo de configuración especifico del usuario.
.It Pa /etc/spectrwm.conf
.Nm
configuraciones globales.
.El
.Sh HISTORIA
.Nm
fue inspirado en xmonad y dwm.
.Sh AUTORES
.An -nosplit
.Nm
fue escrito por
.Pp
.Bl -tag -width "Ryan Thomas McBride Aq mcbride@countersiege.com " -offset indent -compact
.It Cm Marco Peereboom Aq marco@peereboom.us
.It Cm Ryan Thomas McBride Aq mcbride@countersiege.com
.It Cm Darrin Chandler Aq dwchandler@stilyagin.com
.It Cm Pierre-Yves Ritschard Aq pyr@spootnik.org
.It Cm Tuukka Kataja Aq stuge@xor.fi
.It Cm Jason L. Wright Aq jason@thought.net
.It Cm Reginald Kennedy Aq rk@rejii.com
.It Cm Lawrence Teo Aq lteo@lteo.net
.It Cm Tiago Cunha Aq tcunha@gmx.com
.El
